version: "3"

services:
  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: transactions.all

  analyser:
    build: ./analyser
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: transactions.all

      REAL_TRANSACTIONS_TOPIC: transactions.real
      FAKE_TRANSACTIONS_TOPIC: transactions.fake

  websockets_server:
    build: ./websockets_server
    ports:
      - "3000:3000"
    environment:
      KAFKA_BROKER_URL: broker:9092

      REAL_TRANSACTIONS_TOPIC: transactions.real
      FAKE_TRANSACTIONS_TOPIC: transactions.fake

networks:
  default:
    external:
      name: kafka-network