version: "3"

services:
  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: transactions.all

  analyzator:
    build: ./analyzator
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: transactions.all

      REAL_TRANSACTIONS_TOPIC: transactions.real
      FAKE_TRANSACTIONS_TOPIC: transactions.fake

networks:
  default:
    external:
      name: kafka-network